baseURL = "https://faiface.github.io/"
languageCode = "en-us"
title = "faiface blog"
theme = "paperback"
publishDir = "../faiface.github.io/"
disqusShortname = "faiface-github-io"
googleAnalytics = "UA-104415719-1"